### PR TITLE
replaced security with openssl to run on other systems

### PR DESCRIPTION
**Pull request by katunch**
hi 

i've replaced "security" with openssl to run it on other os than mac os x.

### CODE REVIEW

**Comment by matiassingers** [comment]
Awesome PR @katunch - this is really awesome.

I didn't have a chance to test it on any other platform, is it about fully functioning(maybe except for `codesign`)?

----

One small thing:
- [ ] change the `security` mention to `openssl` in the `README`

**Comment by katunch** [comment]
let me do a little test on my ubuntu box... just a sec..

**Comment by katunch** [comment]
Ok i got some news! 
The openssl implementation will not work on other machines because they haven't installed the apple certificates to check against. I will try to bring it up running on a Ubuntu box and will open another pull request. 
Sorry for the inconvenience ;)

**Comment by matiassingers** [comment]
@katunch oh too bad, I wouldn't mind still accepting the PR with the small README change though.

Unfortunate that it doesn't work on other platforms.

**Comment by katunch** [comment]
will open another pull request in a sec

**Comment by matiassingers** [comment]
:+1:

**Pull request closed without merging**
